version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.1.7-node
      - image: cimg/mariadb:10.6
      - image: nginx
    steps:
      - checkout
      - run: php -m
      - run: curl -i http://127.0.0.1/nginx_status
      - run: mariadb --version
